### ISSUE TITLE
Link to workshop materials in readme leads to 404

### ISSUE THREAD

**Issue by jimgar** [joelnitta/penguins-targets#1]
Hi Joel

Thank you for your part in developing and making this workshop available online :)

The following link in the repo readme leads to a 404: https://joelnitta.github.io/targets-workshop/
(Side note, joelnitta.github.io is also a 404)

Is this the intended link? https://carpentries-incubator.github.io/targets-workshop/

**Comment by joelnitta** [comment]
Thanks for catching the error! Yes, the repository got moved so that link is now broken. The correct link is https://carpentries-incubator.github.io/targets-workshop/, and this has now been fixed in the README.
